name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Test
      run: cargo test --verbose
    - name: Check format
      run: |
        if rustup component add rustfmt; then
          cargo fmt --all -- --check
        fi
